
services:
  web: ## services name can be anything...
    build: .
    ports:
      - "8085:80"  ## maps port 80 of the container to port 8085 on the host
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  

  db:
    image: mysql:8.0   ## use mysql image
    restart: always
    environment:
      MYSQL_DATABASE: students
      MYSQL_USER: magento2_user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456

volumes:
  db_data:
